#!/usr/bin/env python3
"""
Recipe Dataset Parser

Takes one or more transcription PDFs (or raw Markdown files) generated by
transcribe.py and extracts structured recipe data into a clean JSON dataset.

When given multiple files the text is merged in the order provided, and
duplicate recipes (same title) are automatically removed so that the final
database is clean even when some pages were re-transcribed separately.

Model fallback chain (for extraction):
  1. OpenRouter: NVIDIA Nemotron 3 Super 120B (free, fast)
  2. Gemini 3 Flash Preview (fastest, most capable)
  3. Ollama qwen3.5:397b-cloud (strong fallback)
  4. Gemini 2.5 Flash (reliable fallback)
  5. Ollama qwen3.5:9b (local, always available)

Output format:
  recipes.json — object with:
    - total_recettes: int
    - recettes: array of recipe objects, each with:
        - titre: recipe title (string, in French)
        - ingredients: list of ingredient strings (in French)
        - preparation: list of preparation step strings (in French)
        - notes: optional string (in French)
        - numero: recipe number in the final database

Usage:
  python parse_recipes.py file1.pdf file2.pdf file3.pdf
  python parse_recipes.py *.pdf --output recipes.json
  python parse_recipes.py *.pdf --output-dir dataset/
  python parse_recipes.py file.md --markdown
"""

import sys
import os
import re
import json
import time
import argparse
import urllib.request
import urllib.error
from pathlib import Path

try:
    import ollama
except ImportError:
    ollama = None

try:
    import pdfplumber
except ImportError:
    pdfplumber = None

try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None


# =============================================================================
# CONFIGURATION
# =============================================================================

DEFAULT_MODEL_CHAIN = [
    "openrouter:nvidia/nemotron-3-super-120b-a12b:free",
    "openrouter:stepfun/step-3.5-flash:free",
    "ollama:qwen3.5:397b-cloud",
    "ollama:qwen3.5:9b",
]

EXTRACTION_PROMPT = """\
Tu es un système expert d'extraction de données culinaires.
Tu reçois le texte brut d'une page d'un cahier de recettes de cuisine manuscrit, en français.
Ton travail est d'extraire les données et de les retourner sous format JSON.

RÈGLES STRICTES :
1. Retourne UNIQUEMENT du JSON valide. Aucun texte, aucune explication, aucune balise markdown.
2. Les clés JSON doivent être exactement : "titre", "ingredients", "preparation", "notes".
3. "titre" : le nom de la recette (string).
4. "ingredients" : une LISTE de strings. Chaque ingrédient est un élément séparé.
   Tu DOIS séparer les ingrédients même si le texte original les met en paragraphe.
5. "preparation" : une LISTE de strings. Chaque étape de préparation est un élément séparé.
   Tu DOIS découper les instructions en étapes individuelles, même si le texte est un long paragraphe.
   Il doit TOUJOURS y avoir au moins 1 étape de préparation. Si le texte contient des instructions
   de cuisson ou de mélange, ce sont des étapes de préparation.
6. "notes" : string pour les conseils ou contexte supplémentaire, ou null si aucun.
7. GARDE TOUT LE TEXTE EN FRANÇAIS. Ne traduis RIEN en anglais.
8. Si le texte ne ressemble pas à une recette, retourne {"error": "not a recipe"}.

EXEMPLE DE SORTIE ATTENDUE :
{"titre": "Gâteau au chocolat", "ingredients": ["200g de chocolat noir", "3 œufs", "100g de beurre"], "preparation": ["Préchauffer le four à 180°C.", "Faire fondre le chocolat et le beurre.", "Battre les œufs et incorporer au mélange."], "notes": null}
"""


# =============================================================================
# TEXT EXTRACTION
# =============================================================================

def extract_text_from_pdf(pdf_path: str) -> str:
    """Extract all text from a PDF file."""
    if pdfplumber is None:
        print("Error: pdfplumber is required. Install with: pip install pdfplumber")
        sys.exit(1)

    text_parts = []
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text_parts.append(page_text)

    return "\n".join(text_parts)


def extract_text_from_markdown(md_path: str) -> str:
    """Read raw Markdown text from a file."""
    with open(md_path, "r", encoding="utf-8") as f:
        return f.read()


def merge_texts(file_paths: list[str], is_markdown: bool = False) -> str:
    """Extract text from each file and merge them together."""
    all_texts = []
    for fp in file_paths:
        print(f"  📄 Reading: {fp}")
        if is_markdown:
            text = extract_text_from_markdown(fp)
        else:
            text = extract_text_from_pdf(fp)
        print(f"      → {len(text)} chars")
        all_texts.append(text)

    return "\n\n".join(all_texts)


# =============================================================================
# CHUNKING
# =============================================================================

def chunk_text_by_recipes(text: str) -> list[str]:
    """
    Split the merged document text into individual recipe chunks.
    Uses '### ' (h3 headings) as the primary delimiter.
    Falls back to heuristic title detection for pdfplumber output.
    """
    chunks = []

    # Try splitting by markdown h3 heading first
    parts = re.split(r'\n###\s+', text)

    if len(parts) > 1:
        if parts[0].strip() and "cahier de recettes" not in parts[0].lower():
            chunks.append(parts[0].strip())
        for part in parts[1:]:
            if part.strip():
                chunks.append(f"### {part.strip()}")
    else:
        # Fallback: pdfplumber may strip markdown.
        lines = text.split("\n")
        current_chunk_lines = []
        for line in lines:
            stripped = line.strip()
            if stripped.lower() in ["cahier de recettes"]:
                continue
            is_title = (
                len(stripped) > 2
                and len(stripped) < 80
                and not stripped.startswith("-")
                and not re.match(r'^\d+[\.)]\s', stripped)
                and not re.match(r'^Page\s+\d+', stripped, re.IGNORECASE)
                and stripped[0].isupper()
                and not any(kw in stripped.lower() for kw in [
                    "ingrédients", "préparation", "ingredients", "preparation",
                    "méthode", "instructions", "étapes",
                ])
                and len(stripped.split()) <= 8
            )
            if is_title and current_chunk_lines:
                chunk = "\n".join(current_chunk_lines).strip()
                if chunk:
                    chunks.append(chunk)
                current_chunk_lines = [f"### {stripped}"]
            else:
                current_chunk_lines.append(line)

        if current_chunk_lines:
            chunk = "\n".join(current_chunk_lines).strip()
            if chunk:
                chunks.append(chunk)

    return chunks


# =============================================================================
# MODEL CALLERS
# =============================================================================

_gemini_client = None


def _get_gemini_client(api_key: str):
    """Lazily create and cache the Gemini client."""
    global _gemini_client
    if _gemini_client is None:
        _gemini_client = genai.Client(api_key=api_key)
    return _gemini_client


def call_gemini(model_name: str, prompt: str, chunk_text: str, api_key: str) -> str:
    """Call Google Gemini API with text. Returns raw text response."""
    client = _get_gemini_client(api_key)
    response = client.models.generate_content(
        model=model_name,
        contents=[prompt + "\n\nVoici le texte à analyser :\n\n" + chunk_text],
        config=types.GenerateContentConfig(temperature=0.1),
    )
    return response.text.strip() if response.text else ""


def call_ollama(model_name: str, prompt: str, chunk_text: str) -> str:
    """Call Ollama with text. Returns raw text response."""
    response = ollama.chat(
        model=model_name,
        messages=[
            {"role": "system", "content": prompt},
            {"role": "user", "content": chunk_text}
        ],
        options={"temperature": 0.1}
    )
    return response.message.content.strip()


def call_openrouter(model_name: str, prompt: str, chunk_text: str, api_key: str) -> str:
    """Call OpenRouter API (OpenAI-compatible). Returns raw text response."""
    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = json.dumps({
        "model": model_name,
        "messages": [
            {"role": "system", "content": prompt},
            {"role": "user", "content": chunk_text}
        ],
        "temperature": 0.1,
    }).encode("utf-8")

    req = urllib.request.Request(url, data=payload, headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=120) as resp:
        data = json.loads(resp.read().decode("utf-8"))

    return data["choices"][0]["message"]["content"].strip()


def _parse_model_spec(spec: str) -> tuple[str, str]:
    """Parse 'provider:model' into (provider, model_name)."""
    if spec.startswith("gemini:"):
        return "gemini", spec[len("gemini:"):]
    elif spec.startswith("ollama:"):
        return "ollama", spec[len("ollama:"):]
    elif spec.startswith("openrouter:"):
        return "openrouter", spec[len("openrouter:"):]
    else:
        return "ollama", spec


def _parse_llm_response(content: str) -> dict | None:
    """Parse raw LLM text into a recipe dict, or None."""
    content = content.strip()

    # Strip <think>...</think> tags
    content = re.sub(r'<think>.*?</think>', '', content, flags=re.DOTALL).strip()

    # Strip markdown code fences
    content = re.sub(r'^```(json)?\s*\n?', '', content)
    content = re.sub(r'\n?```\s*$', '', content)
    content = content.strip()

    data = json.loads(content)

    # Some models return a list instead of a dict — unwrap first element
    if isinstance(data, list):
        if len(data) == 0:
            return None
        data = data[0]

    if not isinstance(data, dict):
        return None

    if "error" in data:
        return None

    recipe = {
        "titre": data.get("titre", "Sans titre").strip(),
        "ingredients": data.get("ingredients", []),
        "preparation": data.get("preparation", []),
        "notes": data.get("notes", None)
    }

    return recipe


def _validate_recipe(recipe: dict, fallback_title: str = "") -> tuple[bool, str]:
    """
    Validate that a recipe has both ingredients and preparation steps.
    If the title is missing, use the fallback_title from the chunk header.
    Returns (is_valid, reason).
    """
    if not recipe.get("titre") or recipe["titre"].strip() == "":
        if fallback_title:
            recipe["titre"] = fallback_title
        else:
            return False, "no title"
    if not recipe.get("ingredients") or len(recipe["ingredients"]) == 0:
        return False, "no ingredients"
    if not recipe.get("preparation") or len(recipe["preparation"]) == 0:
        return False, "no preparation steps"
    return True, "OK"


# =============================================================================
# LLM EXTRACTION WITH FALLBACK
# =============================================================================

def extract_recipe_with_llm(
    chunk_text: str,
    model_chain: list[str],
    api_key: str = "",
    openrouter_key: str = "",
) -> dict | None:
    """
    Try each model in the chain until one returns a valid recipe with
    both ingredients AND preparation steps.
    """
    for model_spec in model_chain:
        provider, model_name = _parse_model_spec(model_spec)

        try:
            start_time = time.time()

            if provider == "openrouter":
                if not openrouter_key:
                    continue
                raw = call_openrouter(model_name, EXTRACTION_PROMPT, chunk_text, openrouter_key)
            elif provider == "gemini":
                if not api_key:
                    continue
                if genai is None:
                    continue
                raw = call_gemini(model_name, EXTRACTION_PROMPT, chunk_text, api_key)
            else:
                if ollama is None:
                    continue
                raw = call_ollama(model_name, EXTRACTION_PROMPT, chunk_text)

            elapsed = time.time() - start_time

            recipe = _parse_llm_response(raw)

            if recipe is None:
                print(f"        [{provider}:{model_name}] ({elapsed:.1f}s) → not a recipe, skipping")
                return None  # Model explicitly said it's not a recipe

            # Extract a fallback title from the chunk header (### Title)
            fallback_title = ""
            first_line = chunk_text.split("\n")[0].strip()
            if first_line.startswith("### "):
                fallback_title = first_line[4:].strip()

            is_valid, reason = _validate_recipe(recipe, fallback_title=fallback_title)
            if is_valid:
                print(f"        [{provider}:{model_name}] ({elapsed:.1f}s) ✓")
                return recipe
            else:
                print(f"        [{provider}:{model_name}] ({elapsed:.1f}s) ✗ {reason}, trying next model...")
                continue

        except Exception as e:
            error_str = str(e).lower()
            is_rate_limit = any(kw in error_str for kw in [
                "429", "rate", "quota", "resource_exhausted", "too many"
            ])
            if is_rate_limit:
                print(f"        [{provider}:{model_name}] ⚡ rate limited, trying next...")
            else:
                print(f"        [{provider}:{model_name}] ✗ error: {e}")
            continue

    return None


# =============================================================================
# DEDUPLICATION
# =============================================================================

def _normalize_title(title: str) -> str:
    """Normalize a recipe title for deduplication comparison."""
    t = title.lower().strip()
    t = re.sub(r'[^a-zàâäéèêëïîôùûüÿçœæ0-9\s]', '', t)
    t = re.sub(r'\s+', ' ', t).strip()
    return t


def deduplicate_recipes(recipes: list[dict]) -> list[dict]:
    """
    Remove duplicate recipes (same normalized title).
    Keeps the version with the most content.
    """
    seen: dict[str, dict] = {}

    for recipe in recipes:
        key = _normalize_title(recipe.get("titre", ""))
        if not key:
            continue

        content_len = (
            sum(len(s) for s in recipe.get("ingredients", []))
            + sum(len(s) for s in recipe.get("preparation", []))
        )

        if key not in seen or content_len > seen[key]["_content_len"]:
            recipe["_content_len"] = content_len
            seen[key] = recipe

    deduped = []
    for i, recipe in enumerate(seen.values()):
        recipe.pop("_content_len", None)
        recipe["numero"] = i + 1
        deduped.append(recipe)

    return deduped


# =============================================================================
# OUTPUT
# =============================================================================

def save_as_json(recipes: list[dict], output_path: str):
    """Save recipes as a single JSON file."""
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump({
            "total_recettes": len(recipes),
            "recettes": recipes,
        }, f, ensure_ascii=False, indent=2)
    print(f"  ✅ JSON: {output_path} ({len(recipes)} recettes)")


def save_as_individual_files(recipes: list[dict], output_dir: str):
    """Save each recipe as an individual JSON file in a directory."""
    dir_path = Path(output_dir)
    dir_path.mkdir(parents=True, exist_ok=True)

    save_as_json(recipes, str(dir_path / "toutes_recettes.json"))

    for recipe in recipes:
        num = recipe["numero"]
        safe_title = re.sub(r'[^\w\s-]', '', recipe["titre"])
        safe_title = re.sub(r'\s+', '_', safe_title).strip('_')[:50]
        filename = f"{num:03d}_{safe_title}.json"

        filepath = dir_path / filename
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(recipe, f, ensure_ascii=False, indent=2)

    print(f"  ✅ Individual files: {output_dir}/ ({len(recipes)} files)")


# =============================================================================
# MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(
        description="Parse one or more recipe transcription PDFs into a structured JSON database.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
Examples:
  # Parse multiple PDFs into a single clean database
  python parse_recipes.py firstp.11.pdf next.83.pdf next.183.pdf

  # Parse all PDFs in the directory
  python parse_recipes.py *.pdf --output recipes.json

  # Save each recipe as an individual file in a folder
  python parse_recipes.py *.pdf --output-dir dataset/

  # Parse from raw Markdown instead of PDF
  python parse_recipes.py transcription.md --markdown

  # Resume a previously interrupted run
  python parse_recipes.py *.pdf --resume
"""
    )
    parser.add_argument("input_files", nargs="+",
                        help="Path(s) to transcription PDF(s) (or Markdown with --markdown)")
    parser.add_argument("--output", "-o", default=None,
                        help="Output JSON file path (default: recipes.json)")
    parser.add_argument("--output-dir", "-d", default=None,
                        help="Output directory for individual recipe files")
    parser.add_argument("--markdown", action="store_true",
                        help="Input is raw Markdown instead of PDF")
    parser.add_argument("--models", nargs="+", default=DEFAULT_MODEL_CHAIN,
                        help="Model fallback chain (default: Nemotron → Gemini 3 → qwen 397b → Gemini 2.5 → qwen 9b)")
    parser.add_argument("--api-key", default=os.getenv("GEMINI_API_KEY", ""),
                        help="Gemini API key (default: env GEMINI_API_KEY)")
    parser.add_argument("--openrouter-key", default=os.getenv("OPENROUTER_API_KEY", ""),
                        help="OpenRouter API key (default: env OPENROUTER_API_KEY)")
    parser.add_argument("--resume", action="store_true",
                        help="Resume parsing from a saved progress file")

    args = parser.parse_args()

    # Validate inputs
    for fp in args.input_files:
        if not os.path.exists(fp):
            print(f"Error: File not found: {fp}")
            sys.exit(1)

    print(f"\n{'='*60}")
    print(f"Recipe Dataset Parser")
    print(f"{'='*60}")
    print(f"Input files: {len(args.input_files)}")
    for fp in args.input_files:
        print(f"  • {fp}")
    print(f"Models: {' → '.join(args.models)}")
    print(f"OpenRouter key: {'set' if args.openrouter_key else 'NOT SET (OpenRouter models will be skipped)'}")
    print(f"Gemini API key: {'set' if args.api_key else 'NOT SET (Gemini models will be skipped)'}")

    # Extract & merge text from all files
    print(f"\n--- Extracting text ---")
    text = merge_texts(args.input_files, is_markdown=args.markdown)

    print(f"\nTotal merged text: {len(text)} chars")
    print(f"{'='*60}\n")

    # Chunk
    chunks = chunk_text_by_recipes(text)
    print(f"Document split into {len(chunks)} potential recipe chunks.\n")

    # Progress saving
    progress_file = Path(".parsing_progress.json")
    recipes = []
    start_index = 0

    if args.resume and progress_file.exists():
        try:
            with open(progress_file, "r", encoding="utf-8") as f:
                saved_state = json.load(f)
                recipes = saved_state.get("recipes", [])
                start_index = saved_state.get("last_processed_index", -1) + 1
                if start_index < len(chunks):
                    print(f"📂 Resuming from chunk {start_index+1}/{len(chunks)} "
                          f"({len(recipes)} recipes done)\n")
                else:
                    print("All chunks were already processed.")
        except Exception as e:
            print(f"Warning: Could not resume from progress file: {e}")

    # Process chunks via LLM
    print("Starting LLM Extraction...\n")

    for i in range(start_index, len(chunks)):
        chunk = chunks[i]
        title_hint = chunk.split("\n")[0][:60]

        print(f"  [{i+1}/{len(chunks)}] {title_hint}")

        recipe_data = extract_recipe_with_llm(chunk, args.models, api_key=args.api_key, openrouter_key=args.openrouter_key)

        if recipe_data:
            recipe_data["numero"] = len(recipes) + 1
            recipes.append(recipe_data)
            print(f"      ✅ {recipe_data['titre']} "
                  f"({len(recipe_data['ingredients'])} ingr., "
                  f"{len(recipe_data['preparation'])} étapes)")
        else:
            print(f"      ⏭️  Skipped (not a valid recipe)")

        # Save progress after every chunk
        with open(progress_file, "w", encoding="utf-8") as f:
            json.dump({
                "last_processed_index": i,
                "recipes": recipes
            }, f, ensure_ascii=False)

    print(f"\n--- Extraction complete ---")
    print(f"Raw recipes extracted: {len(recipes)}")

    if not recipes:
        print("No recipes found. Check the input files or the LLM output.")
        sys.exit(1)

    # Deduplicate
    print(f"\n--- Deduplicating ---")
    before = len(recipes)
    recipes = deduplicate_recipes(recipes)
    after = len(recipes)
    if before != after:
        print(f"  Removed {before - after} duplicate(s).")
    else:
        print(f"  No duplicates found.")
    print(f"  Final: {after} unique recipe(s).\n")

    # Preview
    print("Preview:")
    for r in recipes[:5]:
        ing_count = len(r.get('ingredients', []))
        prep_count = len(r.get('preparation', []))
        print(f"  {r['numero']}. {r['titre']} ({ing_count} ingrédients, {prep_count} étapes)")
    if len(recipes) > 5:
        print(f"  ... et {len(recipes) - 5} de plus\n")
    else:
        print()

    # Save final output
    if args.output_dir:
        save_as_individual_files(recipes, args.output_dir)
    else:
        output_path = args.output or "recipes.json"
        save_as_json(recipes, output_path)

    # Clean up progress file on success
    try:
        if progress_file.exists():
            progress_file.unlink()
    except OSError:
        pass

    print(f"\n{'='*60}")
    print("DONE")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
